# Site settings
title: Yen blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://blog.yclin.me"
twitter_username: yenchenlin1994
github_username:  yenchenlin

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
